name: ia_reel_builder
description: IA Reel Studio Pro V2.0 - Enterprise Marketing Edition
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- EL CEREBRO (IA) ---
  google_generative_ai: ^0.4.0
  provider: ^6.1.1             # Gestiona el estado del Chatbot y la App

  # --- EL MÚSCULO (VIDEO Y ARCHIVOS) ---
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  process_run: ^0.13.0         # Ejecuta ffmpeg.exe nativo en Windows
  image: ^4.1.4                # Compresor para tu procesador Celeron

  # --- LA INTERFAZ (CAPCUT STYLE) ---
  reorderables: ^0.6.0         # Para arrastrar y soltar fotos en el timeline
  audioplayers: ^5.2.1         # Para la Jukebox y pre-escucha
  http: ^1.2.0                 # Para descargar la música de internet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
