name: ia_reel_builder
description: IA Reel Studio Pro V1.2 - Beat Editing & Advanced Jukebox.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  image: ^4.1.4
  http: ^1.2.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
